/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from "@/lib/supabase/server";
import { StorageService } from "@/lib/services/storage";
import type { SavedReport } from "./types";
import { v4 as uuidv4 } from "uuid";
import { createServiceRoleClient } from "@/lib/supabase/server";

/**
 * Report persistence layer handles saving reports to database
 */
export class ReportPersistence {
  private storageService: StorageService;

  constructor() {
    this.storageService = new StorageService();
  }

  /**
   * Save generated report to database
   *
   * @param report - Report content and metadata
   * @param userId - User who generated the report
   * @returns Saved report with ID and slug
   */
  async saveReport(
    report: {
      content: string;
      symbol: string;
      title: string;
      language: string;
      tone: string;
      marketData: any;
    },
    userId?: string
  ): Promise<SavedReport> {
    const supabase = await createClient();

    // Generate IDs
    const reportRunId = uuidv4();
    const slug = this.generateSlug(report.symbol, report.language);

    // Upload report JSON to storage
    const storageResult = await this.storageService.uploadReportJson(reportRunId, {
      content: report.content,
      marketData: report.marketData,
      metadata: {
        symbol: report.symbol,
        language: report.language,
        tone: report.tone,
        generatedAt: new Date().toISOString(),
      },
    });

    // Save to database
    const { data, error } = await supabase
      .from("report_posts")
      .insert({
        report_run_id: reportRunId,
        user_id: userId ?? null,
        symbol: report.symbol,
        title: report.title,
        slug: slug,
        // content: report.content, // Use body field instead
        body: report.content,
        // storage_url: storageResult.publicUrl, // Not in table schema
        tone: report.tone,
        lang: report.language,
        status: "draft",
      })
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to save report: ${error.message}`);
    }

    return {
      id: data.id,
      slug: data.slug,
      report_run_id: reportRunId,
      symbol: data.symbol ?? report.symbol,
      title: data.title,
      content: data.body ?? data.summary ?? "", // Use body or summary as content
      cover_url: data.cover ?? undefined,
      storage_url: undefined, // Not in schema
      tone: report.tone as any,
      language: data.lang as any,
      created_at: data.created_at ?? new Date().toISOString(),
    };
  }

  /**
   * Check if a report can be reused (within 7 days, same params)
   *
   * @param symbol - Stock symbol
   * @param language - Report language
   * @param tone - Report tone
   * @param userId - User ID
   * @returns Existing report if reusable, null otherwise
   */
  async checkReusableReport(
    symbol: string,
    language: string,
    tone: string,
    userId: string
  ): Promise<SavedReport | null> {
    const supabase = await createClient();

    // Check for reports within last 7 days
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    const { data, error } = await supabase
      .from("report_posts")
      .select("*")
      .eq("user_id", userId)
      .eq("symbol", symbol)
      .eq("lang", language)
      .eq("tone", tone)
      .gte("created_at", sevenDaysAgo.toISOString())
      .order("created_at", { ascending: false })
      .limit(1)
      .single();

    if (error || !data) {
      return null;
    }

    return {
      id: data.id,
      slug: data.slug,
      report_run_id: (data as any).report_run_id ?? "",
      symbol: (data as any).symbol ?? symbol,
      title: data.title,
      content: (data as any).content ?? data.body ?? data.summary ?? "",
      cover_url: (data as any).cover_url ?? data.cover ?? undefined,
      storage_url: (data as any).storage_url ?? undefined,
      tone: tone as any,
      language: data.lang as any,
      created_at: data.created_at ?? new Date().toISOString(),
    };
  }

  /**
   * Check for a reusable report generated by any user within a given number of days (e.g., same-day reuse)
   */
  async checkSharedReusableReport(
    symbol: string,
    language: string,
    tone: string,
    maxAgeDays: number = 1
  ): Promise<SavedReport | null> {
    const supabase = await createClient();

    const since = new Date();
    since.setUTCHours(0, 0, 0, 0);
    since.setUTCDate(since.getUTCDate() - (maxAgeDays - 1));

    const { data, error } = await supabase
      .from("report_posts")
      .select("*")
      .eq("symbol", symbol)
      .eq("lang", language)
      .eq("tone", tone)
      .gte("created_at", since.toISOString())
      .order("created_at", { ascending: false })
      .limit(1)
      .single();

    if (error || !data) {
      return null;
    }

    return {
      id: data.id,
      slug: data.slug,
      report_run_id: (data as any).report_run_id ?? "",
      symbol: (data as any).symbol ?? symbol,
      title: data.title,
      content: (data as any).content ?? data.body ?? data.summary ?? "",
      cover_url: (data as any).cover_url ?? data.cover ?? undefined,
      storage_url: (data as any).storage_url ?? undefined,
      tone: tone as any,
      language: data.lang as any,
      created_at: data.created_at ?? new Date().toISOString(),
    };
  }

  /**
   * Generate slug for report URL
   * @private
   */
  private generateSlug(symbol: string, language: string): string {
    const timestamp = Date.now();
    return `${symbol.toLowerCase()}-${language}-${timestamp}`;
  }

  /**
   * Record audit log for report generation
   */
  async recordAudit(userId: string, action: string, details: Record<string, any>): Promise<void> {
    const supabase = await createClient();

    await (supabase as any).from("audit_logs").insert({
      user_id: userId,
      action,
      table_name: "report_posts",
      details,
    });
  }

  /**
   * Load stored market data JSON from storage (if available)
   */
  async getStoredMarketData(reportRunId: string): Promise<any | null> {
    try {
      const supabase = createServiceRoleClient();
      const path = `reports/${reportRunId}.json`;
      const { data, error } = await supabase.storage.from("report-outputs").download(path);
      if (error || !data) return null;
      const text = await data.text();
      const parsed = JSON.parse(text);
      return parsed?.marketData ?? null;
    } catch (err) {
      console.warn("[ReportPersistence] failed to load stored market data:", err);
      return null;
    }
  }
}
